- name:  Install docker and run basic containers
  hosts: all
  become: true

  tasks:
    - name: Install curl, git, htop and docker-compose
      apt:
        name:
          - curl
          - git
          - htop
          - docker-compose
        state: present

    - name: Install Docker
      shell: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh; rm get-docker.sh

    - name: Restart Docker service
      service:
        name: docker
        state: restarted

    - name: Clone Docker demo repository
      git:
        repo: https://github.com/aattilam/docker-demo
        dest: /opt/docker-demo
      when: ansible_os_family == 'Debian'
      
    - name: Create containers
      command: docker-compose up -d
      args:
        chdir: /opt/docker-demo
      when: ansible_os_family == 'Debian'
      
    - name: Remove Docker demo directory
      file:
        path: /opt/docker-demo
        state: absent
      when: ansible_os_family == 'Debian'
